--- #YAML:1.0
name:                Bundle-Music-Tag
version:             0.01
abstract:            Music::Tag bundle for quick installation
license:             ~
author:              
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
